# FTS Touchscreen Configuration
# Enables wake-on-touch for UDFPS
# Generated by udfps_screen_off_wake Magisk module

touch.deviceType = touchScreen
touch.orientationAware = 1
device.external = 0
device.wake = 1
